name: Build and Deploy Angular to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: |
        # Build مستقیم داخل dist_nasb
        npm run build -- --configuration=production --output-path=dist_nasb --delete-output-path --no-prerender

    - name: Clean target folder on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          sudo rm -rf /var/www/timedari.ir/browser/* 

    - name: Deploy built files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        source: dist_nasb/*
        target: /var/www/timedari.ir/browser/

    - name: Set permissions and restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          sudo chown -R www-data:www-data /var/www/timedari.ir/browser
          sudo chmod -R 755 /var/www/timedari.ir/browser
          sudo systemctl restart nginx
