name: Build and Deploy Angular to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --configuration=production --no-prerender

    - name: Clean old frontend files on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          sudo rm -rf /var/www/timedari.ir/*

    - name: Deploy built files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        source: dist/timedari-frontend/browser/*
        target: /var/www/timedari.ir/

    - name: Finalize deployment (rename + permissions + restart)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          if [ -f /var/www/timedari.ir/index.csr.html ]; then
            sudo mv -f /var/www/timedari.ir/index.csr.html /var/www/timedari.ir/index.html
          fi
          sudo chown -R www-data:www-data /var/www/timedari.ir
          sudo chmod -R 755 /var/www/timedari.ir
          sudo systemctl restart nginx
