# .github/workflows/deploy-angular.yml

name: Build and Deploy Angular to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --configuration=production --no-prerender

    - name: Deploy to VPS via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        source: dist/timedari-frontend/
        target: /var/www/timedari.ir

    - name: Restart Nginx (optional)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          sudo systemctl restart nginx
