name: Build and Deploy Angular to VPS

on:
  push:
    branches: [ main, develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          npm run build -- --configuration=production --no-prerender
        else
          npm run build -- --configuration=development --no-prerender
        fi

    - name: Deploy built files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        # مسیر دقیق browser نهایی داخل dist
        source: dist/timedari-frontend/browser/timedari-frontend/browser/*
        target: ${{ github.ref == 'refs/heads/main' && '/var/www/timedari.ir/browser' || '/var/www/dev-timedari-frontend/browser' }}

    - name: Set permissions and restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            TARGET=/var/www/timedari.ir/browser
          else
            TARGET=/var/www/dev-timedari-frontend/browser
          fi
          sudo chown -R www-data:www-data $TARGET
          sudo chmod -R 755 $TARGET
          sudo systemctl restart nginx
